# Requires JDK 17+. Maven 4.0.0-rc-5. Wrapper 3.3.4+ required for Maven 4 compatibility.
distributionUrl=https://maven.aliyun.com/repository/central/org/apache/maven/apache-maven/4.0.0-rc-5/apache-maven-4.0.0-rc-5-bin.zip
wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.3.4/maven-wrapper-3.3.4.jar
